// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
// // import Link from 'next/link';
// // import { usePathname } from 'next/navigation';
// // import { motion } from 'framer-motion';

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// const navItems = [
//   { href: '/photos', label: 'Photos' },
//   { href: '/videos', label: 'Videos' },
//   { href: '/about', label: 'About' },
//   { href: '/contact', label: 'Contact' },
// ];

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//     // const pathname = usePathname();

//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//          {/* <motion.nav
//           initial={{ y: -50, opacity: 0 }}
//           animate={{ y: 0, opacity: 1 }}
//           transition={{ duration: 0.5 }}
//           style={{
//             display: 'flex',
//             justifyContent: 'center',
//             gap: '2rem',
//             padding: '1rem 0',
//             backgroundColor: '#111',
//           }}
//         >
//           {navItems.map(({ href, label }) => (
//             <motion.div
//               key={href}
//               whileHover={{ scale: 1.1, color: '#ff0055' }}
//               style={{ listStyle: 'none' }}
//             >
//               <Link
//                 href={href}
//                 style={{
//                   color: pathname === href ? '#ff0055' : '#eee',
//                   textDecoration: 'none',
//                   fontWeight: pathname === href ? 'bold' : 'normal',
//                   fontSize: '1.2rem',
//                 }}
//               >
//                 {label}
//               </Link>
//             </motion.div>
//           ))}
//         </motion.nav>
//         <main
//           style={{
//             maxWidth: '1200px',
//             margin: '2rem auto',
//             padding: '0 1rem',
//             minHeight: '80vh',
//           }}
//         > */}
//         {children}
//         {/* </main> */}
//       </body>
//     </html>
//   );
// }


// layout.tsx - Root layout con stile fotografico
// import './globals.css';
// import type { Metadata } from 'next';
// import { Inter } from 'next/font/google';
// import Navbar from './components/Navbar';

// const inter = Inter({ subsets: ['latin'] });

// export const metadata: Metadata = {
//   title: 'J.D. Studio – Portfolio',
//   description: 'Fine art & lifestyle photography by Jacopo D.',
// };

// export default function RootLayout({ children }: { children: React.ReactNode }) {
//   return (
//     <html lang="en">
//       <body className={`bg-white text-neutral-800 ${inter.className}`}>
//         <Navbar />
//         <main className="pt-24 px-6 pb-12 max-w-5xl mx-auto min-h-screen">
//           {children}
//         </main>
//       </body>
//     </html>
//   );
// }


// layout.tsx - Root layout con stile fotografico
import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import localFont from 'next/font/local';
import Navbar from './components/Navbar';

const playfair = localFont({
  src: './fonts/PlayfairDisplay-Regular.ttf',
  display: 'swap',
  variable: '--font-serif',
});

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'J.D. Studio – Portfolio',
  description: 'Fine art & lifestyle photography by Jacopo D.',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      {/* <body className={`bg-[#fdfaf6] text-neutral-800 ${inter.className}`}> */}
      <body
  className={`bg-[#fdfaf6] text-neutral-800 font-sans ${playfair.variable}`}
  style={{ fontFamily: 'var(--font-serif)' }}
>
        <Navbar />
        <main className="pt-24 px-6 pb-12 max-w-5xl mx-auto min-h-screen">
          {children}
        </main>
      </body>
    </html>
  );
}